# Generated by Django 3.0 on 2019-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='food_choices',
            field=models.CharField(choices=[('Fast Food', 'Fast Food'), ('Bar Attached', 'Bar Attached'), ('Bakery', 'Bakery'), ('Normal', 'Normal')], default='Normal', max_length=50),
        ),
    ]
